package calculofiguras;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.RoundingMode;
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author estudiantes
 */

public class interfazGrafica extends javax.swing.JFrame {
    String welcomeText = "<html>Selecciona de la lista una de las figuras geometricas<BR>Ingresa los parametros y calcula su area y perimetro<BR>Dibuja la figura.</html>";   
    Graficas grafPanel = new Graficas();
    
    public interfazGrafica() {
        initComponents();
        //welcomeLabel.setText = "Bienvenido! A continuacion podra seleccionar de la lista una de las figuras geometricas, luego podra ingresar los parametros de la figura y calcular su are y perimetro y dibujar dicha figura.";
        Graficas.CleanPanel(tablero.getGraphics());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor..
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tablero = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        calcularLabel = new javax.swing.JLabel();
        graficarLabel = new javax.swing.JLabel();
        calcularLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Figuras Geometricas");
        setResizable(false);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por favor elija una figura.", "Cuadrado.", "Circulo.", "Triangulo.", "Rectangulo." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Radio:");

        jLabel2.setText("Altura:");

        jLabel5.setText("Area:");

        jLabel6.setText("Perimetro:");

        tablero.setFocusCycleRoot(true);

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Graficar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Selecciona de la lista una de las figuras geometricas.");

        calcularLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcularLabel.setText("Ingresa los parametros");

        graficarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        graficarLabel.setText("Dibuja la figura");

        calcularLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcularLabel1.setText("Calcular Area y Perimetro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(395, 395, 395))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(graficarLabel)))
                                .addGap(164, 164, 164))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(calcularLabel))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(calcularLabel1)
                        .addGap(399, 399, 399))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLabel)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1)
                .addGap(18, 18, 18)
                .addComponent(calcularLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graficarLabel)
                    .addComponent(calcularLabel1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String textFigura = "";
        String label = "";
        String label2 = "";
        switch(jComboBox1.getSelectedIndex()){
           case 0:
               textFigura = "Por favor escoga una opción";
               label="";
               label2="";
               this.jLabel1.setText(label);
               this.jLabel2.setText(label2);
               this.jTextField1.setVisible(false);
               this.jTextField2.setVisible(false);
               this.jTextField1.setText("");
               this.jTextField2.setText("");
               this.jLabel7.setText("");
               this.jLabel8.setText("");
               Graficas.CleanPanel(tablero.getGraphics());
               break;
           case 1:
               textFigura = "Cuadrado";
               label="Lado:";
               label2="";
               this.jLabel1.setText(label);
               this.jLabel2.setText(label2);
               this.jTextField1.setVisible(true);
               this.jTextField2.setVisible(false);
               this.jTextField1.setText("");
               this.jTextField2.setText("");
               this.jLabel7.setText("");
               this.jLabel8.setText("");
               Graficas.CleanPanel(tablero.getGraphics());
               break;
           case 2:
               textFigura = "Circulo";
               label="Radio:";
               label2="";
               this.jLabel1.setText(label);
               this.jLabel2.setText(label2);
               this.jTextField1.setVisible(true);
               this.jTextField2.setVisible(false);
               this.jTextField1.setText("");
               this.jTextField2.setText("");
               this.jLabel7.setText("");
               this.jLabel8.setText("");
               Graficas.CleanPanel(tablero.getGraphics());
               break;
           case 3:
               textFigura = "Triangulo";
               label="Lado:";
               label2="";
               this.jLabel1.setText(label);
               this.jLabel2.setText(label2);
               this.jTextField1.setVisible(true);
               this.jTextField2.setVisible(false);
               this.jTextField1.setText("");
               this.jTextField2.setText("");
               this.jLabel7.setText("");
               this.jLabel8.setText("");
               Graficas.CleanPanel(tablero.getGraphics());
               break;
           case 4:
               textFigura = "Rectangulo";
               label="Base:";
               label2="Altura:";
               this.jLabel1.setText(label);
               this.jLabel2.setText(label2);
               this.jTextField1.setVisible(true);
               this.jTextField2.setVisible(true);
               this.jTextField1.setText("");
               this.jTextField2.setText("");
               this.jLabel7.setText("");
               this.jLabel8.setText("");
               Graficas.CleanPanel(tablero.getGraphics());
               break;
       }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       double lado = 0.0;
       double base = 0.0;
       String input1 = "";
       String input2 = "";
       input1 = this.jTextField1.getText(); 
       input2 = this.jTextField2.getText(); 
       
       if(input1 != null && !input1.isEmpty()){
           lado = Double.parseDouble(input1);
       }else{
           lado = 0.0; 
       }
       if(input2 != null && !input2.isEmpty()){
           base = Double.parseDouble(input2);
       }else{
           base = 0.0;
       }
       
       String area = "";
       String perimetro = "";
       calculo calcular = new calculo();
      
       calcular.setLado(lado);
       calcular.setBase(base);      
        
        switch(jComboBox1.getSelectedIndex()){
          case 0:
              break;
          case 1:
              perimetro = Double.toString(calculo.cuadrado_perimetro(lado));               
              area = Double.toString(calculo.cuadrado_area(lado));               
              //Graficas.DibujarCuadrado(tablero.getGraphics(), 20);
              break;
          case 2:
              perimetro = Double.toString(calculo.circulo_perimetro(lado));
              area = Double.toString(calculo.circulo_area(lado));
              break;
          case 3:
              perimetro = Double.toString(calculo.triangulo_perimetro(lado));
              area = Double.toString(calculo.triangulo_area(lado));
              break;
          case 4:
              perimetro = Double.toString(calculo.rectangulo_perimetro(lado,base));
              area = Double.toString(calculo.rectangulo_area(lado,base)); 
              break;
        }         
       this.jLabel7.setText(perimetro);
       this.jLabel8.setText(area);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int lado = 0;
        int base = 0;
        String input1 = "";
        String input2 = "";
        
        input1 = this.jTextField1.getText(); 
        input2 = this.jTextField2.getText();
        
        if(input1 != null && !input1.isEmpty()){
            lado = Integer.parseInt(input1);
        }else{   
            lado = 0; 
        }
        
        if(input2 != null && !input2.isEmpty()){
           base = Integer.parseInt(input2);
        }else{ 
            base = 0;
        }
        
        grafPanel.setLado(lado);
        grafPanel.setBase(base);       
        
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                break;
            case 1:  
                Graficas.CleanPanel(tablero.getGraphics());
                Graficas.DibujarCuadrado(tablero.getGraphics(), lado);            
                break;
            case 2:
                Graficas.CleanPanel(tablero.getGraphics());
                Graficas.DibujarCirculo(tablero.getGraphics(), lado);
                break;
            case 3:
                Graficas.CleanPanel(tablero.getGraphics());
                Graficas.DibujarTriangulo(tablero.getGraphics(), lado);
                break;
            case 4:
                Graficas.CleanPanel(tablero.getGraphics());
                Graficas.DibujarRectangulo(tablero.getGraphics(), base, lado);
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcularLabel;
    private javax.swing.JLabel calcularLabel1;
    private javax.swing.JLabel graficarLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel tablero;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
